// Mocks generated by Mockito 5.4.2 from annotations
// in todo_sprint/test/features/todo/data/repositories/todo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_sprint/features/todo/data/datasources/todo_local_data_source.dart'
    as _i3;
import 'package:todo_sprint/features/todo/domain/entities/todo.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodo_0 extends _i1.SmartFake implements _i2.Todo {
  _FakeTodo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoLocalDataSource extends _i1.Mock
    implements _i3.TodoLocalDataSource {
  MockTodoLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Todo>> getAllTodos() => (super.noSuchMethod(
        Invocation.method(
          #getAllTodos,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Todo>>.value(<_i2.Todo>[]),
      ) as _i4.Future<List<_i2.Todo>>);
  @override
  _i4.Future<_i2.Todo> getTodoById(String? todoId) => (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [todoId],
        ),
        returnValue: _i4.Future<_i2.Todo>.value(_FakeTodo_0(
          this,
          Invocation.method(
            #getTodoById,
            [todoId],
          ),
        )),
      ) as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> createTodo({
    required String? title,
    required String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTodo,
          [],
          {
            #title: title,
            #description: description,
          },
        ),
        returnValue: _i4.Future<_i2.Todo>.value(_FakeTodo_0(
          this,
          Invocation.method(
            #createTodo,
            [],
            {
              #title: title,
              #description: description,
            },
          ),
        )),
      ) as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> updateTodo(
    String? todoId, {
    String? title,
    String? description,
    bool? isComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [todoId],
          {
            #title: title,
            #description: description,
            #isComplete: isComplete,
          },
        ),
        returnValue: _i4.Future<_i2.Todo>.value(_FakeTodo_0(
          this,
          Invocation.method(
            #updateTodo,
            [todoId],
            {
              #title: title,
              #description: description,
              #isComplete: isComplete,
            },
          ),
        )),
      ) as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<String> deleteTodo(String? todoId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodo,
          [todoId],
        ),
        returnValue: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
}
